#!/bin/bash

# Setup script for WordPress automation
# This creates your wordpress_config.sh file with your credentials

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE="$SCRIPT_DIR/wordpress_config.sh"

echo "════════════════════════════════════════════════════════"
echo "     WordPress Configuration Setup"
echo "════════════════════════════════════════════════════════"
echo ""

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Configuration file already exists at:"
    echo "   $CONFIG_FILE"
    echo ""
    read -p "Overwrite existing configuration? (yes/no): " overwrite
    if [ "$overwrite" != "yes" ]; then
        echo "Cancelled. Existing configuration preserved."
        exit 0
    fi
    echo ""
fi

# Get WordPress username
echo "Enter your WordPress.com username or email:"
read -p "> " wp_username

# Get Application Password (note: we'll paste it directly into the config)
echo ""
echo "Paste your WordPress Application Password:"
echo "(It looks like: xxxx xxxx xxxx xxxx xxxx xxxx)"
read -p "> " wp_app_password

# Remove spaces from the app password
wp_app_password_clean=$(echo "$wp_app_password" | tr -d ' ')

# Get page IDs (optional for now)
echo ""
echo "Optional: Enter your WordPress homepage page ID"
echo "(You can find this in the URL when editing the page in wp-admin)"
echo "(Leave blank to skip for now)"
read -p "> " homepage_id

echo ""
echo "Optional: Enter your WordPress features page ID"
echo "(Leave blank to skip for now)"
read -p "> " features_id

# Create the config file
cat > "$CONFIG_FILE" << EOF
#!/bin/bash

# WordPress.com Configuration
# Generated by setup_wordpress.sh on $(date)
# ⚠️  KEEP THIS FILE SECRET - It contains your credentials!

# Your WordPress.com site URL (without trailing slash)
WP_SITE_URL="https://moltenglass.app"

# Your WordPress.com username
WP_USERNAME="$wp_username"

# Your WordPress.com Application Password
WP_APP_PASSWORD="$wp_app_password_clean"

# Page IDs to update (find these in WordPress admin URL when editing pages)
WP_HOMEPAGE_ID="$homepage_id"
WP_FEATURES_PAGE_ID="$features_id"

# Optional: Social media configuration (for future use)
TWITTER_ENABLED=false
INSTAGRAM_ENABLED=false
EOF

# Make the config file executable and secure
chmod 600 "$CONFIG_FILE"

echo ""
echo "✅ Configuration saved to:"
echo "   $CONFIG_FILE"
echo ""
echo "🔒 File permissions set to 600 (owner read/write only)"
echo ""
echo "Next steps:"
echo "  1. Test the configuration: ./test_wordpress_connection.sh"
echo "  2. Generate and publish screenshots: ./publish_screenshots.sh"
echo ""
