#!/bin/bash

# Set build number to git commit count
# This script is run as a build phase in Xcode to automatically
# set CFBundleVersion to the current git commit count.

# Navigate to source root
cd "${SRCROOT}"

if [ -d ".git" ]; then
    BUILD_NUMBER=$(git rev-list --count HEAD)
    SHORT_HASH=$(git rev-parse --short HEAD)

    # Update the Info.plist in the built app (if it exists)
    if [ -f "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" ]; then
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
        echo "✅ Build number set to: $BUILD_NUMBER (commit count)"
    fi

    # Also generate a Swift file that can be read at compile time
    # This ensures the build number is always accurate
    GENERATED_FILE="${SRCROOT}/Molten/Sources/Generated/BuildInfo.swift"
    mkdir -p "$(dirname "$GENERATED_FILE")"

    cat > "$GENERATED_FILE" << EOF
//
//  BuildInfo.swift
//  Molten
//
//  Auto-generated by set-build-number.sh - DO NOT EDIT
//

import Foundation

/// Build information generated at compile time
enum BuildInfo {
    /// Git commit count (build number)
    static let buildNumber = "$BUILD_NUMBER"

    /// Short git commit hash
    static let gitHash = "$SHORT_HASH"

    /// Combined version string (e.g., "3536 (abc1234)")
    static var fullBuildString: String {
        "\(buildNumber) (\(gitHash))"
    }
}
EOF

    echo "✅ Generated BuildInfo.swift with build $BUILD_NUMBER ($SHORT_HASH)"
else
    echo "⚠️  Not a git repository, skipping build number update"
fi
